import test, { expect } from "@playwright/test"

test("file upload in salesforce", { tag: '@smoke' }, async ({page}) => {
   // test.slow()
    await page.goto('https://testleaf-da-dev-ed.develop.lightning.force.com/lightning/page/home')
    await page.locator("#username").fill("vidyar@testleaf.com")
    await page.locator("#password").fill("Sales@123")
    await page.locator("#Login").click()
    await page.waitForLoadState('load')
    await page.getByTitle("App Launcher").click({ timeout: 5000 })
    await page.getByRole('button').getByText("View All").click()
    await page.getByPlaceholder("Search apps or items...").fill("Accounts")
    await page.locator('//mark').click()
    await page.locator('[title="New"][role="button"]').click()
    await page.locator('[name="Name"]').fill("Rajesh_Test")
    await page.locator('button[aria-label="Rating"]').click()
    await page.getByTitle('Warm').click()
    await page.locator('button[aria-label="Type"]').click()
    await page.getByTitle('Prospect').click()
    await page.locator('button[aria-label="Industry"]').click()
    await page.getByTitle('Banking').click()
    await page.locator('button[aria-label="Ownership"]').click()
    await page.getByTitle('Public').click()
    await page.locator('button[name="SaveEdit"]').click() 
    const accountname = await page.locator('lightning-formatted-text[slot]').innerText()
    console.log(accountname)
    const filePromise= page.waitForEvent('filechooser')
    await page.locator('span[part="button"] > lightning-primitive-icon').click()
    const fileupload=await filePromise;
    await fileupload.setFiles("./tests/homeAssignments/2.jpg")
    await page.locator('button[type="button"] > span[dir=ltr]').last().click()
    await expect(page.locator('span[title="2"]')).toBeVisible()
})